name: Run Jupyter Notebook

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install 
      run: make install

    - name: Install Jupyter Notebook
      run: |
        pip install jupyter nbconvert
      # You can specify the version or other dependencies here.

    - name: Run Notebook
      run: |
        jupyter nbconvert --execute --to notebook --inplace main.ipynb
      # Replace 'notebook.ipynb' with the path to your notebook.

    - name: Check for changes
      id: check_changes
      run: |
        git diff --exit-code || echo "Changes found"
      continue-on-error: true

    - name: Commit and push changes
      if: steps.check_changes.outputs.return-code == '0'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add main.ipynb
        git commit -m "Auto-generated notebook execution"
        git push
